---
language: 'python'
python: '2.7'
# don't send email notification
email: false
sudo: false

install:
  # installs ansible
  - sudo pip install ansible

  # Sets the upper directory as roles container
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
