---
- include: dependencies.yml

- name: downloads glassfish package
  get_url: 
    url: "{{ gf_url }}" 
    dest: "/tmp/glassfish-{{ gf_version }}.zip"

- name: creates the glassfish group
  sudo: true
  group: 
    name: glassfish 
    state: present

- name: creates the glassfish user
  sudo: true
  user: 
    name: glassfish 
    group: glassfish 
    state: present 
    system: true 
    append: true

- name: unzips glassfish package
  sudo: true
  unarchive: src=/tmp/glassfish-{{ gf_version }}.zip dest={{ gf_install_dir }}
  
- name: changes group owner of the glassfish folder
  file:
    path: "{{ gf_install_dir }}"
    owner: "{{ gf_user }}"
    group: "{{ gf_group }}"
