---
- name: installs unzip and java
  apt: name={{ item }} state=latest
  with_items:
    - unzip
    - openjdk-7-jre

- name: downloads glassfish package
  get_url: url=http://download.java.net/glassfish/{{ gf_version }}/release/glassfish-{{ gf_version }}.zip dest=/tmp/glassfish-{{ gf_version }}.zip

- name: creates the glassfish group
  group: name=glassfish state=present

- name: creates the glassfish user
  user: name=glassfish group=glassfish state=present system=true append=yes

- name: unzips glassfish package
  unarchive: src=/tmp/glassfish-{{ gf_version }}.zip dest=/opt owner=glassfish
